### ISSUE TITLE
clear not working on already cleared sheet

### ISSUE THREAD

**Issue by nattelog** [theoephraim/node-google-spreadsheet#104]
Is this a bug or a feature?

**Comment by macrozone** [comment]
this throws an error

```
 TypeError: Cannot read property 'setValue' of undefined
```

clearly a bug to me

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
