### ISSUE TITLE
addRow with `id`

### ISSUE THREAD

**Issue by dhoeric** [theoephraim/node-google-spreadsheet#107]
Hi all,

I cannot addRow with a column name `id`, is there any reserved word in column name?

```
sheet.addRow({
        'id': 333,
        ...
});
```

**Comment by Voronchuk** [comment]
Hey, just in case you plan to do anything with the created row object, this maybe [useful](https://github.com/theoephraim/node-google-spreadsheet/pull/108) for you.

**Comment by theoephraim** [comment]
This has been a known limitation for quite a while. Now that I have a decent test suite, I'll see about tackling this problem!

**Comment by dhoeric** [comment]
Thanks for replying, I have just create another column (`SELECT *, id AS another_id FROM ...`) to workaround.

**Comment by odub** [comment]
I also just hit this problem. It would be nice to get an error if `id` is a reserved word.

**Comment by mddanishyusuf** [comment]
I also faced this issues but I use 'Id' and it's worked for me.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
