### ISSUE TITLE
useServiceAccountAuth curently requires a string not JSON

### ISSUE THREAD

**Issue by sradforth** [theoephraim/node-google-spreadsheet#110]
In the example text it shows
var creds = require('../token.json');
doc.useServiceAccountAuth( creds, function()

but this gives an error from Google saying key not found. Turns out it should be a string version passed in rather than the JSON.  
A quick fix is just modify the docs but perhaps the userServiceAccountAuth should convert JSON to a string internally?

Below appears to work fine.
var creds = require('../token.json');
doc.useServiceAccountAuth( JSON.stringify( creds ), function( params )

**Comment by objectiveSee** [comment]
If you pass a string then it must be the path of the module you want to require (ie. credentials.json). Otherwise pass

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
