### ISSUE TITLE
Issue using with browserify - cannot find module './aes'

### ISSUE THREAD

**Issue by Mauredo** [theoephraim/node-google-spreadsheet#133]
Hi,

Every time I try to use google-spreadsheet, following your tutorial, I always end up with this error:

> bundle.js:1 Uncaught Error: Cannot find module './aes'

I've tried to install aes by npm manually and it's not working.

I've tried to check for solutions online and it looks like it's something related to integration with browserify which I also use.

Can you please help?

**Comment by theoephraim** [comment]
I haven't tested integration with browserify at all :(
So actually if you want to hit the spreadsheets API from the browser, you probably want to use the oauth flow to get permissions for a user instead of the service account flow (which is made for server to server communication (the backend of your application).

Very happy to accept a PR if you get it working though!

**Comment by dariusk** [comment]
I just ran into this bug myself. It's because this module has `node-forge` in its dependency tree:

```
├─┬ google-spreadsheet@2.0.3 (git://github.com/dariusk/node-google-spreadsheet.git#843e3910c7b6465a3a703dafe8c3c69e7e74ef7b)
│ ├── async@1.5.2
│ ├─┬ google-auth-library@0.9.8
│ │ ├── async@1.4.2  
│ │ ├─┬ gtoken@1.2.1 
│ │ │ ├─┬ google-p12-pem@0.1.0
│ │ │ │ └── node-forge@0.6.42
```

`node-forge` doesn't work with `browserify` and produces this error. It's still an outstanding bug in `node-forge`: https://github.com/digitalbazaar/forge/issues/294

If I come up with a PR I'll submit, of course.

**Comment by dileepkeeppalli** [comment]
@dariusk I was trying to use this node-forge in Ionic 2 application. 
`cannot find module './aes'` this same error I am getting. 

Ionic 2 application is in typescript and angular2. The same node-forge I have used in pure angular2 application and it worked fine.

I dont have any idea that why it is it giving this error when I am trying to to use node-forge in Ionic2 applicationn. 

Please help me on this

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
