### ISSUE TITLE
Auth working on windows but not on production linux vm

### ISSUE THREAD

**Issue by cfullerton** [theoephraim/node-google-spreadsheet#141]
I'm using the json file method. It's part of a larger app that makes a lot of calls to other web services so I don't think it's the machine's access to the internet. I'm using the same file on both.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
