### ISSUE TITLE
google_auth.expires is undefined

### ISSUE THREAD

**Issue by bitliner** [theoephraim/node-google-spreadsheet#145]
The fun part is that locally on my laptop it works fine.

When I run the same module on the server, it fails throwing the error message in the title.

**Comment by bitliner** [comment]
Some more elements:

* the program runs in Docker
* restarting the container, it does not solve the issue
* restarting docker does

Do you experience the same?

**Comment by jake-walker** [comment]
Yes, I get the same problem on Windows 10 x64:
```
...\node_modules\google-spreadsheet\index.js:114
    if(google_auth.expires > +new Date()) return step();
                  ^

TypeError: Cannot read property 'expires' of undefined
    at auth (...\node_modules\google-spreadsheet\index.js:114:24)
    at ...\node_modules\async\lib\async.js:718:13
    . . .
```

**Comment by hllwd** [comment]
Hey there, I've encountered the same issue on my computer, the problem was because my clock was 5 minutes in advance, making this `if (google_auth.expires > +new Date()) return step();` fail

**Comment by jake-walker** [comment]
ok thanks!

**Comment by ksenzee** [comment]
When I ran into this, it was because I had passed in the wrong .json file for my credentials. Maybe some more robust error checking would be useful during the auth process.

**Comment by zouhairkhallaf** [comment]
I was getting this error because I was calling the API functions outside my doc.useServiceAccountAuth() function. Make sure you call the API function inside it.
This example works: 
var GoogleSpreadsheet = require('google-spreadsheet');
var creds             = require('./client_secret.json');

// Create a document object using the ID of the spreadsheet - obtained from its URL.
var doc = new GoogleSpreadsheet('someSheetID');

// Authenticate with the Google Spreadsheets API.
doc.useServiceAccountAuth(creds, function (err) {
  if(err)
    console.log(err)
  // Get all of the rows from the spreadsheet.
  doc.getRows(1, function (err, rows) {
    console.log(rows);
  });
  doc.addRow(1,{someKeyToUpdate: 'someNewData'}, function(err) {
    if(err) {
      console.log(err);
    }
  });
});




BUT THIS THROWS AN ERROR:

var GoogleSpreadsheet = require('google-spreadsheet');
var creds             = require('./client_secret.json');

// Create a document object using the ID of the spreadsheet - obtained from its URL.
var doc = new GoogleSpreadsheet('someSheetID');

// Authenticate with the Google Spreadsheets API.
doc.useServiceAccountAuth(creds, function (err) {
  if(err)
    console.log(err)
  // Get all of the rows from the spreadsheet.
  doc.getRows(1, function (err, rows) {
    console.log(rows);
  });
});

doc.addRow(1,{someKeyToUpdate: 'someNewData'}, function(err) {
  if(err) {
    console.log(err);
  }
});
