### ISSUE TITLE
How to get values of the same type inside the Spreadsheet?

### ISSUE THREAD

**Issue by bitliner** [theoephraim/node-google-spreadsheet#146]
My sheet includes multiple type of data:
* boolean
* integer
* string

When I access the data with this library, it returns only string.

How to get values according to real types of the spreadsheet?

**Comment by christopherclark** [comment]
You'll need to write a couple functions to convert those yourself, I would imagine.  google sheets doesn't know the difference between a boolean and a string. so,  for example  if(x = "true"){ x = true).

**Comment by theoephraim** [comment]
Right so the sheet doesn't do any type validation. If you are fetching cells (instead of full rows) you can use the `numericValue` property, but again, its not enforced.

If you know the types of your columns, you should just do the conversion on your end.

If you are looking for a spreadsheet with some proper type validation, check out https://airtable.com/ -- it's very cool and super useful!
