### ISSUE TITLE
Http 500 Internal Server errror

### ISSUE THREAD

**Issue by rustanacexd** [theoephraim/node-google-spreadsheet#158]
I am getting this issue sometimes - http://take.ms/QQSrA

**Comment by avimar** [comment]
I'm seeing a few HTTP 500s also.

Generally, the calls work, so I generally didn't have any need for `catch()`.

Is there a way to make a retry on every `500` response? Perhaps a configurable retry time/backoff...

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
