### ISSUE TITLE
Unhandled Error when status code 302 is returned

### ISSUE THREAD

**Issue by nmehta6** [theoephraim/node-google-spreadsheet#161]
I am randomly seeing failures due to Google Sheets API returning status code 302. This happens for me on the addRow operation. Retrying to add the same row succeeds. The response body looks like this:

```
<HTML>
<HEAD>
<TITLE>Moved Temporarily</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Temporarily</H1>
The document has moved <A HREF="https://spreadsheets.google.com/feeds/list/1FfG5x47urhsVJ2gVCiJB0Xk1Vou0IkGFxcsIQ3UHGbU/od6/private/full?lsrp=1">here</A>.
</BODY>
</HTML
```

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄

**Comment by nmehta6** [comment]
@theoephraim Much appreciated! I will test out the new version.
