### ISSUE TITLE
npm WARN deprecation: node-uuid@1.4.8: Use uuid module instead

### ISSUE THREAD

**Issue by binomialstew** [theoephraim/node-google-spreadsheet#162]
This is just a warning, but node-uuid has been deprecated and is a dependency of this package as of version 2.0.4. Here is the [discussion](https://github.com/kelektiv/node-uuid/issues/142) in the node-uuid page.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
