### ISSUE TITLE
removeWorksheet missing parameter, so callback not called

### ISSUE THREAD

**Issue by scottp** [theoephraim/node-google-spreadsheet#169]
This code, calls makeFeedRequest with 3 parameters, where as makeFeedRequest takes 4 parameters. This means that the callback goes into query_or_data. Adding a null fixes that.

```
  this.removeWorksheet = function ( worksheet_id, cb ){
    if (!this.isAuthActive()) return cb(new Error(REQUIRE_AUTH_MESSAGE));
    self.makeFeedRequest( ["worksheets", ss_key, worksheet_id], 'DELETE', cb );
  }
```

Simple fix

```
  this.removeWorksheet = function ( worksheet_id, cb ){
    if (!this.isAuthActive()) return cb(new Error(REQUIRE_AUTH_MESSAGE));
    self.makeFeedRequest( ["worksheets", ss_key, worksheet_id], 'DELETE', null, cb );
  }
```

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
