### ISSUE TITLE
.del() function for rows returns undefined

### ISSUE THREAD

**Issue by joshuaquek** [theoephraim/node-google-spreadsheet#181]
Is there a way to know that the row has been deleted? Like maybe add a callback method for this so that code can be executed once the row is successfully deleted? 

Hope to hear from you soon.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
