### ISSUE TITLE
getRows() not working (any more)?

### ISSUE THREAD

**Issue by mj321** [theoephraim/node-google-spreadsheet#184]
getRows() always returns 0 rows for me.
getCells() however does work.

**Comment by jorisw** [comment]
Remove empty rows from the beginning of your sheet.

**Comment by jasonhargrove** [comment]
In my case rows 2 and 3 were empty, with data on rows 1 and 4.
Removing rows 2 and 3 resulted in data being returned.
Opinion: Workaround is not really a great solution. a: people use empty rows b: API user may not have ability to remove empty roles, even if they wanted to

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄

**Comment by trogmaniac** [comment]
Thanks!

**Comment by mj321** [comment]
Thanks!
