### ISSUE TITLE
Minor bug in SpreadsheetWorksheet.clear()

### ISSUE THREAD

**Issue by richard-sim** [theoephraim/node-google-spreadsheet#195]
There's a minor bug in SpreadsheetWorksheet.clear() where the original row count is actually the column count, which later gets incorrectly restored:

https://github.com/theoephraim/node-google-spreadsheet/blob/master/index.js#L400

**Comment by myovchev** [comment]
Maybe related, leading to unhandled error `Cannot read property 'setValue' of undefined` when calling .clear in my code:
https://github.com/theoephraim/node-google-spreadsheet/blob/master/index.js#L404

**Comment by endel** [comment]
I'm also having this error (`TypeError: Cannot read property 'setValue' of undefined`) is there any workaround for this?

**Comment by Daniel-M** [comment]
Can confirm this bug too

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
