### ISSUE TITLE
Throwing captcha in response?

### ISSUE THREAD

**Issue by petulla** [theoephraim/node-google-spreadsheet#202]
I'm getting a captcha response after using the sheet package. How do you bypass?

I'm using a service account.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
