### ISSUE TITLE
bulkUpdateCells is slow and uses too much memory

### ISSUE THREAD

**Issue by macrozone** [theoephraim/node-google-spreadsheet#206]
Hi,

I need to create spreadsheets with up to 50'000 rows (with 15 columns). I try to push it chunk by chunk by using `sheetSync.bulkUpdateCells` with different amount of rows. But even 500 rows take a minute to push. Also, after some chunks (at around 7000 rows) have been sent, my process get out of memory.

the memory problem might be mitigated by https://github.com/theoephraim/node-google-spreadsheet/pull/182 (will check), but i still wonder why it is so slow. Is there a way to make it faster? 

EDIT: The raw amount of uploaded data could also be limiting. Is the upload compressed?

**Comment by macrozone** [comment]
it seems that v4 of the google api should be much faster. Any plan to migrate?

**Comment by josh-renton** [comment]
I'm thinking of forking this to update to the latest Google API, @theoephraim isn't responding.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
