### ISSUE TITLE
index.js Causes Webpack Warning: Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by jwhiteaei** [theoephraim/node-google-spreadsheet#221]
The node module "./node_modules/google-spreadsheet/index.js" causes the following Webpack warning: 
"Critical dependency: the request of a dependency is an expression"

**Comment by PEZO19** [comment]
Same here.

**Comment by acm1264** [comment]
I was having a similar issue, and after looking through their code, I found that in index.js, the useServiceAccountAuth function has some code where, if you give your credentials for the spreadsheet as a string instead of using an object, it will "require" the creds. If you are setting up your creds (api key) as an object in a json file, for example, you can just comment out this extra code since it won't be relevant to you, and it removes the warning.
`this.useServiceAccountAuth = function( creds, cb ){

    // if (typeof creds == 'string') {
    //   try {
    //     creds = require(creds);
    //   } catch (err) {
    //     return cb(err);
    //   }
    // }

    jwt_client = new auth_client.JWT(creds.client_email, null, creds.private_key, GOOGLE_AUTH_SCOPE, null);
    renewJwtAuth(cb);
  }`

**Comment by theoephraim** [comment]
This module was not really designed to be used on the front-end. It was also built before webpack was really a thing :)

Not to say it couldn't be used on the front-end, but probably a lot more rare that this is the case.

If this is a blocker, I could introduce a breaking change that removes this feature and just expects the user to required the creds themselves and pass them in.

**Comment by acm1264** [comment]
On my end, I found I had to implement the change in the above comment while I tested my code originally, but once I set it all up with an API it worked fine with post requests on the back-end without changing anything like you stated. In case people do want to utilize this code purely through the front-end, however, that change may help them!

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
