### ISSUE TITLE
TypeError: Cannot read property '$' of undefined

### ISSUE THREAD

**Issue by vivekghanchi** [theoephraim/node-google-spreadsheet#225]
While going through the example code this error occurred while executing this code

**Comment by vivekghanchi** [comment]
```
 function managingSheets(step) {
    doc.addWorksheet({
      title: 'my new sheet'
    }, function(err, sheet) {

      // change a sheet's title
      sheet.setTitle('new title'); //async

      //resize a sheet
      sheet.resize({rowCount: 50, colCount: 20}); //async

      sheet.setHeaderRow(['name', 'age', 'phone']); //async

      // removing a worksheet
      sheet.del(); //async

      step();
    });
  }
```

this code is giving this error

**Comment by andersonad** [comment]
The source of this error is due to the function calls being async. In this case delete can happen before the others. We can fix this with a mild callback hell:
```
   function managingSheets(step) {
    doc.addWorksheet({
      title: 'my new sheet'
    }, function(err, sheet) {

      // change a sheet's title
      sheet.setTitle('new title', function () {

        //resize a sheet
        sheet.resize({rowCount: 50, colCount: 20}, function () {

          sheet.setHeaderRow(['name', 'age', 'phone'], function () {

            // removing a worksheet
            sheet.del(); //async
          })
        })
      });

      step();
    });
  }

```

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
