### ISSUE TITLE
 jwt_client.authorize is not calling

### ISSUE THREAD

**Issue by jjhesk** [theoephraim/node-google-spreadsheet#232]
there is no return from  jwt_client.authorize..

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
