### ISSUE TITLE
Can’t white Half -width character

### ISSUE THREAD

**Issue by keito-prg** [theoephraim/node-google-spreadsheet#241]
Today I used google spread sheet .
I can't type a Half-width character smoothy.
In Half-width character , and  I   finish type in cell.
I want to write next cell.then this  cell is not active.
so I can 't  type a Half-width character smoothy.

if it's not bug , I think but UI.
also if google spread sheet have to Configuration, It's confusing.

I use Mac book Air and visit by safari

I hope your further improvement

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
