### ISSUE TITLE
Easy way to get rows length

### ISSUE THREAD

**Issue by rajavijayavendan** [theoephraim/node-google-spreadsheet#258]
How to get rows length instead of getting all rows and then finding the length. Is there any easy way?

**Comment by boutdemousse** [comment]
It's in the `SpreadsheetWorksheet` object, property `rowCount` and it's counterpart `colCount`.
When invoking `getInfo()` you get the information in the `worksheets` array.

**Comment by rajavijayavendan** [comment]
@boutdemousse Thanks a lot.

**Comment by rajavijayavendan** [comment]
> It's in the `SpreadsheetWorksheet` object, property `rowCount` and it's counterpart `colCount`.
> When invoking `getInfo()` you get the information in the `worksheets` array.

@boutdemousse, the property rowCount in SpreadsheetWorksheet object provides an incorrect row count. In our sheet we have only 300 odd rows populated but the above attribute gives 1000 odd.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).
**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Regardless, you do have to fetch the rows in order to check how many are non-empty
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
