### ISSUE TITLE
useless expression typeof( self[key] == 'string')

### ISSUE THREAD

**Issue by vadzim** [theoephraim/node-google-spreadsheet#263]
There is useless expression
```js
typeof( self[key] == 'string')
```
in the `if` condition:

https://github.com/theoephraim/node-google-spreadsheet/blob/f261e0cf3bec5f8e7ae2396b7274a4702e373130/index.js#L518

It always evaluates to the non-empty string `'boolean'` and thus is always truthy.

**Comment by vadzim** [comment]
I haven't push PR because I'm not sure if this can be safely fixed to
```js
typeof(self[key]) == 'string'
```
because it seems it can lead to incompatibility with some existing codes.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).

Docs available here - https://theoephraim.github.io/node-google-spreadsheet

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
