### ISSUE TITLE
On row saving, the cells with the "dollar" sign corrupts the values

### ISSUE THREAD

**Issue by vinodhreddygs** [theoephraim/node-google-spreadsheet#270]
Hi,

While updating and then save() any column value, the other cell values (other than updating cell) which contains the special characters "$"  corrupts the cell values.

1. Please refer the below screen shot which **colored in the yellow**.(The values with dollars getting the corrupts from **$75.00 to $75.00.00** etc.(**examples: $11.01 to $11.01.01, S22.22 to $22.22.22.22**).

![gSheet_Issue](https://user-images.githubusercontent.com/37541181/72865373-97d60700-3cfd-11ea-8d5e-2c369e03bbf2.jpg)

2.Please refer below code snippet that I'am using for updating cell in row and then saving using **save()**.

```
 return getRecordToUpdate(cost, name, state, county, sheetInfo)
            .then((updateRec) => {
                if(updateRec.length > 0) {
                    var prodDescCol= prodDesc.replace(/ /g,'').toLowerCase();
                    if(updateRec[0].hasOwnProperty(prodDescCol)) {
                        if(updateRec[0][prodDescCol].replace("$", "").trim() != cost) {
                            updateRec[0][prodDescCol] = cost;
                            return Promise.promisify(updateRec[0].save)()  
                        } else return;
                    } else return;                         
                
                } else return;                 
            })
```

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020).

Docs available here - https://theoephraim.github.io/node-google-spreadsheet

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
