### ISSUE TITLE
Migration guide or changelog

### ISSUE THREAD

**Issue by whaatt** [theoephraim/node-google-spreadsheet#273]
Hi there! I noticed you just published a version of this library compatible with Google Sheets V4.

At a first glance, what do existing codebases using this library need to do to migrate from the old version? It looks like a number of functions no longer take callbacks (and return `Promise`s instead), but is there anything else that is materially different?

If there's a changelog, that'd be awesome.

Thanks!

**Comment by theoephraim** [comment]
I had considered it, but figured the effort would be better spent on making sure the general docs were really solid. I'll see if I can make some time to get something together, but in general quite a lot has changed, but I've tried to make sure it still is very simple. Google's v4 api is very different so some things really had to change.

- everything is promise based so no more callbacks (promises are now much better with async/await)
- when fetching rows, you can no longer use queries or ordering (google no longer supports the row-based calls, so I had to recreate them as much as possible)
  - also the issue with an empty row breaking things is now gone, but empty rows will be fetched
- use `doc.loadInfo()` which loads props that live on the doc, rather than returning the info with `doc.getInfo()`
- cell interaction is very different, but should be even easier to use
  - load cells with `sheet.loadCells()` (can use a filter like `sheet.loadCells('A1:F10')`)
  - access specific cells with `sheet.getCell(row, col)` or `sheet.getCellByA1('D5')`
  - make changes `cell.value = "newValue"` or `cell.formula = "=SUM(A1:D1)"`
  - save all unsaved changes using `sheet.saveUpdatedCells()`

**Comment by deepfriedbrain** [comment]
I'm also trying to migrate my project to Google Spreadsheet v4. The documentation of this library mentions `getCells` to get all cells, but when I call it, I get an error 'getCells is not a function', and I can't find that function in the code either. What function should I use to get all the cells?

**Comment by theoephraim** [comment]
Hello! Must be a typo - it’s loadCells

**Comment by whaatt** [comment]
Another idea (purely a suggestion/feature request, I'm sure there are many other things competing for your attention): Would be awesome to have TypeScript type definitions for this library!

**Comment by theoephraim** [comment]
going to close as it's now been quite a while. I've also added a changelog file and will keep it up to date as we move forward!

Thanks :D
