### ISSUE TITLE
addRow with Promise.all bug

### ISSUE THREAD

**Issue by olehcambel** [theoephraim/node-google-spreadsheet#294]
I'm trying to create `addRows` method using Promise.all and bottleneck to prevent from rate limit. However, it works strange and inserts into one cell by replacing previous value. 

```js
const { GoogleSpreadsheet } = require('google-spreadsheet');

const googleSpreadsheet = new GoogleSpreadsheet(config.gsheets.sheetid);

await googleSpreadsheet.useServiceAccountAuth({
    client_email: config.gsheets.clientEmail,
    private_key: config.gsheets.privateKey,
});

await googleSpreadsheet.loadInfo();

const sheet = await googleSpreadsheet.addSheet({ headers: ['name'] });
const promises = [];

for (let i = 0; i < 40; i++) {
    // will work without issue
    // await sheet.addRow({ name: `name_${i}` });
    promises.push(sheet.addRow({ name: `name_${i}` }));
}

await Promise.all(promises);
```

Result:
```
name
name_0
name_11
name_33
```

**Comment by theoephraim** [comment]
Since youre doing them in parallel, I dont think you can guarantee what order google will receive or process them in. 2 things
- may I sugges https://github.com/caolan/async for all your async control flow needs. `asnyc.eachLimit` is quite cool :)
- it should be pretty trivial to add an `addRows` function that appends more than 1 row at a time in a single API call. I don't have time tonight but should be able to get to it this week. Feel free to try yourself and add a PR if you feel like it! :D

**Comment by theoephraim** [comment]
I added an `addRows` method which is capable of adding many rows with a single api call.
Please check it out and let me know if you encounter any bugs.

https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-addrows

Cheers!

**Comment by olehcambel** [comment]
Thanks! Previously, I didn't know that V4 allows you bulk insert. Yeah, it works great
