### ISSUE TITLE
Trialing comma breaks importing into coffeescript

### ISSUE THREAD

**Issue by ThrowsException** [theoephraim/node-google-spreadsheet#297]
the trailing comma lint rule causes issues when trying to import this into coffeescript and using an older node version (6.11)
 https://github.com/eslint/eslint/issues/7749

This unfortunately prevents me from using the module or submitting a PR to fix since removing the comma on GoogleSpreadsheet.js:39 breaks the linting rule. 

Any chance you would reevaluate this rule?

**Comment by theoephraim** [comment]
Well, I wouldn't consider getting rid of trailing commas in general, because I think it's just more consistent and keeps diffs smaller.

BUT it appears the issue may only have to do with trailing commas on multiline function params, which is pretty rare, and kind of weird anyway. Ive pushed up a branch, so you can test it before I commit the change and bump the version.

Try replacing the dependency in your package.json file with `theoephraim/node-google-spreadsheet#no-dangling-comma-functions` and let me know if that fixes it!

**Comment by ThrowsException** [comment]
Yup that fixes the issue.

**Comment by theoephraim** [comment]
just published the update to npm.
Cheers!
