### ISSUE TITLE
How to merge cells ?

### ISSUE THREAD

**Issue by Zglorb** [theoephraim/node-google-spreadsheet#310]
Hello,
I've made an whole project based on this package but now we ask me to do formatting like merging cells together. I haven't found something helpfull about this in the docs.
Is there a way to do it with this package or do i need to switch to the official google api's package ?
(Sorry, if this is not the place to ask those type of questions)
thanks in advance.

**Comment by theoephraim** [comment]
I haven't implemented all of the newer methods in the v4 sheets api yet, but it should be pretty trivial to get this added.

Feel free to open a PR - otherwise I'll try to get to it in the next week or so.

https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#MergeCellsRequest

**Comment by Zglorb** [comment]
thank you for your answer
