### ISSUE TITLE
await sheet.addRow() function turn into row.save()

### ISSUE THREAD

**Issue by kevin51034** [theoephraim/node-google-spreadsheet#316]
HI,the question is my **sheet.addRow() function will update one of the row in my sheet**
the api works in old version.However,when I trying to update to the version(3.0.8), the addRow method always update one row in my sheet

some code 
```
const sheet = doc.sheetsByIndex[4]
const newrow = {
        key: `${value}`,
    }
const addNewRow = await sheet.addRow(newrow);
```

all method like save,get is working,but the addRow method turn into save even I didn't call getRow in this function,and it will automatically choose one row and update the value.
is there anywhere I can fix this problem?Thanks!

**Comment by theoephraim** [comment]
I'm not sure I fully understand your question but this may help:

When you call sheet.addRow, by default it uses the "overwrite" method, meaning it will look for the first empty row and fill that one in - adding an extra row to the sheet if all rows have something in them. If it's overwriting a non-empty row, perhaps it could be because you are doing other things to the sheet at the same time?

If it is overwriting an empty row, and you just want it to insert a new row instead. You can use the insert option if you want it to add a new row to the sheet instead.
See https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-addrow
`sheet.addRow({ col1: 'something' }, { insert: true })`
