### ISSUE TITLE
query or filter values range cells

### ISSUE THREAD

**Issue by dverdugo85** [theoephraim/node-google-spreadsheet#346]
Its posible to do a query ... to search value in a Range or cells for example only return values before to date

**Comment by theoephraim** [comment]
Unfortunately, not that I'm aware of. Google deprecated their row-based API in the latest version, and I just did my best to recreate the methods. But this means I couldn't support the row-based query methods they had before.

You could likely set it up so that you filters although this would actually change the filters on the sheet.
You could also use formulas?

For example, sheet 1 is your source data, sheet 2 uses a formula to filter sheet 1 data to match your query.

Hope that helps!
