### ISSUE TITLE
Working on draftData

### ISSUE THREAD

**Issue by Faberle** [theoephraim/node-google-spreadsheet#350]
If we write to the same cell twice without calling `sheet.saveUpdatedCells()` we get the Error ` 'Value has been changed'` due to https://github.com/theoephraim/node-google-spreadsheet/blob/95c3271b250bf4f9d99651a8269d1f76719e2168/lib/GoogleSpreadsheetCell.js#L37

Wouldn't it also be possible to just return the `_draftData.value` if it's not undefined?
Or am I missing something?

**Comment by theoephraim** [comment]
So the issue here is that updating the value may result in multiple changes that we can't fully predict until we save. For example, if the cell uses a formula, I can't know what the new value is going to be. I also can't know what the formatted value may be (unless we try to recreate all of google's formatting logic).

The idea of throwing that error is to make sure it's clear that the cell is in this unsaved state.

What is your use case? Perhaps I can help figure out a workaround.

**Comment by Faberle** [comment]
In my use case there was only data in the cells, so I applied a workaround to a fork and worked with that.  
I was trying to use a google speadsheet as a database in a Proof of Concept.  
I can not recommend it! 😅

**Comment by theoephraim** [comment]
Yeah I originally wrote this module to do something similar...
Now for similar things, I would recommend using something like https://airtable.com/
