### ISSUE TITLE
Broken auth (Twilio serverless)

### ISSUE THREAD

**Issue by hochmanjoel** [theoephraim/node-google-spreadsheet#357]
I've been trying to implement this package in a serverless Twilio Node.js function. For the life of me, I cannot get auth to work. I downloaded the correct credential json then uploaded it as an asset on Twilio. I've logged it so I know it is there correctly. The Promise keeps rejecting. If I use `require()` , then the error is `Cannot find module` and if it is not used, then I get a `No key or keyfile set`.
![Screen Shot 2020-06-05 at 10 52 17 AM](https://user-images.githubusercontent.com/22176573/83897016-a35d2400-a71a-11ea-953d-93dc9abfa40d.png)

**Comment by hochmanjoel** [comment]
@theoephraim

**Comment by theoephraim** [comment]
Ok so on ething is if youre using async/await, then you dont need to call `.catch` instead wrap the call in a try/catch.

Also, it may be that `creds` is being read in as a string, and you need to first call `JSON.parse` on it to turn it into an object. Alternatively, I'm not sure how the twilio serverless world works, but I assume you can probably set env variables from their UI? In which case you can save the email and token from the json file as env vars and pass those in, rather than needing the whole json file (see the example here - https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication?id=service-account)

**Comment by hochmanjoel** [comment]
I needed to `JSON.parse`. Thanks!
