### ISSUE TITLE
How to authenticate with OAuth?

### ISSUE THREAD

**Issue by razafinarivohanania** [theoephraim/node-google-spreadsheet#373]
Hello, i attempt to connect on spreedsheet with OAuth authentication but i'm blocked. I created my OAuth, and this JSON file `client_id.json` was downloaded.

```json
{
    "web": {
        "client_id": "****.apps.googleusercontent.com",
        "project_id": "****",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": "****"
    }
}
```

I naively use the JSON file from :

```js
// OR load directly from json file if not in secure environment
await doc.useServiceAccountAuth(require('./creds-from-google.json'));
```

I just change the `creds-from-google.json` with `client_id.json`. But when i run my application i've got this error :

```
(node:12795) UnhandledPromiseRejectionWarning: Error: No key or keyFile set.
    at GoogleToken.getTokenAsync (/home/myapp/node_modules/gtoken/build/src/index.js:125:19)
    at GoogleToken.getToken (/home/myapp/node_modules/gtoken/build/src/index.js:77:21)
    at JWT.refreshTokenNoCache (/home/myapp/node_modules/google-auth-library/build/src/auth/jwtclient.js:156:36)
    at JWT.refreshToken (/home/myapp/node_modules/google-auth-library/build/src/auth/oauth2client.js:143:25)
    at JWT.authorizeAsync (/home/myapp/node_modules/google-auth-library/build/src/auth/jwtclient.js:139:35)
    at JWT.authorize (/home/myapp/node_modules/google-auth-library/build/src/auth/jwtclient.js:135:25)
    at GoogleSpreadsheet.renewJwtAuth (/home/myapp/node_modules/google-spreadsheet/lib/GoogleSpreadsheet.js:86:26)
    at GoogleSpreadsheet.useServiceAccountAuth (/home/myapp/node_modules/google-spreadsheet/lib/GoogleSpreadsheet.js:81:16)
    at /home/myapp/index.js:10:15
    at Object.<anonymous> (/home/myapp/index.js:18:3)
```
I wonder if there is fonction like `useOAuth()`. My google-spreadsheet version is 3.0.11. Thank you in advance :)

**Comment by theoephraim** [comment]
This json document is not the same as a service account. It is possible to connect via oauth, but there is not nice built-in support and I do not have a good example. Will try to add it in the next batch of work

**Comment by razafinarivohanania** [comment]
Thanks for response. I'll wait.

**Comment by max-sv-ma** [comment]
@theoephraim 
Hi, also waiting for this support

**Comment by alxndr** [comment]
Also curious about how to set up a read-only API token for client-side read-only use... IAM? OAuth? Not sure what's appropriate, and Google seems to have changed things up since the last update to [the Auth doc](https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication?id=api-key).

**Comment by JacobRichardson** [comment]
### **I am getting the same 403 error.**

The error is as follows:
Google API error - [403] The caller does not have permission.

### I am not sure what the best way to authenticate is in order to access my own personal spreadsheets. 
what is the best way to just access personal spreadsheets? I am not trying to create an application to access other people's spreadsheets. Rather, a program to read and modify data into my own spreadsheets.

### The method I tried:

I created a service account, gave the correct role or owner (I tried changing it to other roles such as viewer and adding admin roles and it did not work), created a key, **shared the google spreadsheet with the client_email**, and attempted to authenticate using the example in the README.md. I am still getting a 403 error.

I used this library about 10 months ago using the v3 API and it was working properly. I spent a bunch of time tonight trying to figure out why it wasn't working. I forgot the last time that I used the library, I shared the spreadsheet (going to my google drive -> spreadsheet -> clicking share in the top right corner) with the service accounts email. I did this now and it appears to still not be working.

I am assuming this is an issue with node-google-spreadsheet and not an error on Google's end?

### Code
This is the code I am running:
```js
// Imports.
require('dotenv').config();
const GoogleSpreadsheet = require('google-spreadsheet').GoogleSpreadsheet;
const creds = require('./creds.json');

// Async function.
(async function () {

    // Retrieve the doc using the spreadsheet id.
    const doc = new GoogleSpreadsheet(process.env.SPREADSHEET_ID);

    // Use the Google generated file from the key on the service account.
    await doc.useServiceAccountAuth(creds);

    // This is were the error is occurring.
    // Load the document 
    await doc.loadInfo();

})();
```

### .env File

I obtained the spreadsheet id from the URL in my google drive. Replacing <spreadsheet_id> with the actual id of the spreadsheet.

The .env file in the project contains:
SPREADSHEET_ID=<spreadsheet_id>

**Comment by benoror** [comment]
Hey @theoephraim, thanks for your work on this project!

> It is possible to connect via oauth, but there is not nice built-in support and I do not have a good example

Any chance to document the workaround before a nice wrapper is developed?

On the other hand, any hints where to look at if someone would like to open a proposal PR for it? 

Thanks, cheers!

**Comment by benoror** [comment]
Maybe implementing a `useOauth()` authentication method that leverages on [`useRawAccessToken(token)`](https://github.com/theoephraim/node-google-spreadsheet/blob/b2275eba33616e880c8fea376a32561e2cec4ea0/docs/classes/google-spreadsheet.md#userawaccesstokentoken-idfn-userawaccesstoken) behind the scenes?

**Comment by theoephraim** [comment]
Oauth support is now published - check out https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication?id=oauth for more info

@JacobRichardson @alxndr - if you are still having problems, please open new issues!

**Comment by benoror** [comment]
Awesome thanks @theoephraim !

**Comment by darcy-vitacca** [comment]
For anyone trying to auth through a .env i had to use this process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n')  for the key as the \n newlines weren't getting picked up when  requesting to google

**Comment by sometimescasey** [comment]
Thanks for the tip @darcy-vitacca ! FWIW I am using a local `.env` file and didn't need to do this, but will see what happens upon deploy to Heroku. Will update here if anything changes.

In my case I was getting `[403] The caller does not have permission` but the error was much more simple 🤦  - I was previously using a publicly viewable sheet and I switched it to private.

If you do this, you need to add the `GOOGLE_SERVICE_ACCOUNT_EMAIL` to your list of viewers or editors in the actual Google sheet itself (the same way that you would share with a friend).

Seems obvious now but I'm not sure if it was mentioned in the docs?
