### ISSUE TITLE
Why I can't read a draft value?

### ISSUE THREAD

**Issue by g-borgulya** [theoephraim/node-google-spreadsheet#402]
Hi! Here's my use-case:
When I work with spreadsheets using the API, my biggest problem is the API rate limitation.

If I just work with a handful of rows to do calculations on and update some values, and work with rows in this library, then updates are saved to the spreadsheet immediately, and after a couple of interactions the Google API refuses to handle the requests.

So my workaround for that is to work with cells: I'm loading the related cells to my script, read/write what I want, and then using saveUpdatedCells I just save everything. That works, no API overload anymore.

Now the limitation that I have comes from this package: I can't re-read any cached cell values that were already updated. This makes the logic of working with cells sometimes quite complicated.

For the first sight looking in the source it seems getCell() could simply return the draftValue instead of the real value in this case. Instead it raises an error. Is there any reason for having this hard constrain here? Can it be simply removed?

https://github.com/theoephraim/node-google-spreadsheet/blob/301dfa9fb128c7bb28ab13e40005823c23cd55bf/lib/GoogleSpreadsheetCell.js#L37

**Comment by theoephraim** [comment]
Hi @g-borgulya!

So the issue here is that updating the value may result in multiple changes that we can't fully predict until we save. For example, if the cell uses a formula, I can't know what the new value is going to be. I also can't know what the formatted value may be (unless we try to recreate all of google's formatting logic).

The idea of throwing that error is to make sure it's clear that the cell is in this unsaved state.

For your use-case, could you just read `cell._draftData.value || cell.value`?

**Comment by theoephraim** [comment]
Going to close this off for now. Would a section in the docs explaining this help clarify?
