### ISSUE TITLE
_isDirty, saveUpdatedCells, and rapid cell update

### ISSUE THREAD

**Issue by christopherreay** [theoephraim/node-google-spreadsheet#412]
### symptoms

cell values which are updated during the `saveUpdatedCells` process do not get recognised as `_isDirty` on subsequent calls to `saveUpdatedCells`

### discussion
I have built a workaround myself, in which I store updates to cells that happen during the async call to `saveUpdatedCells` and then write them to the cells afterwards. This works as expected.

I went through the code from the point of `saveUpdatedCells`, but I was unable to find the code which deletes the value in `cell._draftData`. 

> in principal, the two operations:
> * interpretation of each `_draftData` (or other `_isDirty` reasons) to its part of the `_makeBatchUpdateRequest` `string` 
> * and the setting of that `_draftData` to `undefined`
>
> must be fully atomic.

I wish I could find where it should be!

Thank you for the great library

**Comment by theoephraim** [comment]
Hello!

I just took a look at the code. Here is some info about what is happening:
(doc = GoogleSpreadsheet, sheet = GoogleSpreadsheetWorksheet, cell = GoogleSpreadsheetCell)
- sheet.saveUpdatedCells - filters dirty cells, which uses cell._draftData
- sheet.saveCells - batches together many save requests
- doc._makeBatchUpdateRequest - makes the requests, updates the doc/sheet data from the response
- doc._updateOrCreateSheet - creates or updates sheet info and then cell data
- sheet._fillCellData - loops through the returned data creating/updating cells
- cell._updateRawData - updates the cell data from google, resets cell._draftData

If I understand correctly, the issue is that updates that were made in between triggering `saveUpdatedCells` and that save finishing are being overwritten when the update finishes. Is that correct?

What is your use case?
In your code, can you not just wait for the save to finish before continuing?
Would it make sense to set up this module to instead throw an error if any cells that are mid-update are attempted to be changed?

If neither of these solutions will work, we can try to set up something to track the draftData that is saving and clear it right away.

**Comment by christopherreay** [comment]
I think that throwing an error on cell updates that are currently being written would be functional.

Any other answer makes assumptions as the the ultimate semantic of the app using the library.

The solution that I am using is to have my own dictionary that stores a second level of "draft" that is updated consistently. This is on the basis that for my usecase, I am only interested in storing the latest value of the cell.

It seems conceivable that there would be a use case in which someone wanted to ensure the sequence of values written to the sheet was consistent, in which case throwing an error is really the only posisbility. 
Good catch :)

So on that basis, the flag against the cell that would cause an error to be thrown on writing a new value. really I would say that this should be a synchronous operation, and that saveUpdatedCells should be a synchronous function on that basis. But the edge case where that is important is probably extremely unlikely.

Thank you for your time :)
