### ISSUE TITLE
Export JS data to a new Google spreadsheet

### ISSUE THREAD

**Issue by tqdo** [theoephraim/node-google-spreadsheet#415]
I wonder whether the library supports exporting data from JS (either an array or an object) to a new Google spreadsheet that can be shared with others? I looked around the doc but could not find any info about that functionality

**Comment by theoephraim** [comment]
I dont quite follow. There is no one-step export to a new doc, but you can create a new sheet and populate the data.
Although the sheets API doesnt let you control sharing, so that may be a blocker. You'd have to use the Drive API for that, and while this module does not currently support it, I'd love to add that in the future.
