### ISSUE TITLE
Question: is it possible to update a row searching for a specific value?

### ISSUE THREAD

**Issue by StErMi** [theoephraim/node-google-spreadsheet#417]
I would like to understand if there's a way to update records that have already been added into the sheet looking for the row that has a specific value in a cell. Is it possible to do that or the only way is to delete all and replace everything?

**Comment by Romans96** [comment]
Hi! I did it with this function, hope this is what you need.
If i have a sheet with this value:
0  col1 col2 col3 col4
1  v1    v2    v3    v4
2  a1    a2    a3    a4
```
myFunc: async function(sheet, value, colName) {
        let allRows = await sheet.getRows();
        for (let i = 1; i < allRows.length; i++) { // Data rows start at index 1
            if (allRows[i].colName == value) {
                return i;
            }
        }
    },
```
This returns the relative row with a specific value, into a specific column (colName), of a specific sheet object. Then when i call it:
`let myRow = await myFunc(sheet, "a2", col2);`

then i've my row and i go to modify it (i want to modify the value on column col1)
with `myRow.col1 = "hello";`

then i need to save the modified row:
`await myRow.save();`

(Remember you cannot use this method in Sheet with imported column (that are imported form other sheet)), because you overwrite that row and the import on each column gives error.

**Comment by StErMi** [comment]
Hi @Romans96 I don't think that this is a viable option if you have a sheet with 150K rows :(

**Comment by theoephraim** [comment]
Google's API doesnt really support searching through the sheet data. But depending on your requirements, you could try to use formulas to do the searching. Basically, you have your source data in one sheet, and you use a formula (like [VLOOKUP](https://support.google.com/docs/answer/3093318)) in another sheet to find the row/cell/etc that you are looking for. Then read that formula result to know which row you need to read/update.

Of course this isn't appropriate for all cases, but might work depending on your needs.
