### ISSUE TITLE
Separate auth from library

### ISSUE THREAD

**Issue by LeGmask** [theoephraim/node-google-spreadsheet#527]
The idea is to create another package (or just use something that already exist) and separate the auth from this module. Since this package is fully Javascript (browser) and  nodejs compliant why keep a package that break the compatibility for Javascript (browser) support .... 

I currently use this project in a webapp without backend and no other solution than patching (by removing google-auth) to finally have webpack successfully compile ...

Anyway good jobs, that's a nice project.
Best regards

**Comment by theoephraim** [comment]
It's been on my to-do list for a while. I think the best way would be to use rollup to create 2 different builds, one for the browser and one for backend. But currently since there is no build process at all, it's a bit of a project... I'll see if maybe there is a simpler way as you suggest to just remove the google auth library, but I do like keeping the DX as simple as possible for most users.

**Comment by LeGmask** [comment]
Yeah, In fact I've allready removed google auth for my project and that's work well : https://github.com/LeGmask/node-google-spreadsheet

But yeah the auth wrapper is pretty good  and simple tho. I understand the idea to keep it simple and I'm fully agree with you since I use this library because of is simplicity since all the others libs are horrible to use ...

**Comment by theoephraim** [comment]
@LeGmask - I just finally released a typescript rewrite with many improvements and one of them was decoupling the google-auth-library. Thanks so much for the suggestion and discussion.

Cheers!
