### ISSUE TITLE
check if has access to view or edit, or both

### ISSUE THREAD

**Issue by konkersgg** [theoephraim/node-google-spreadsheet#536]
I couldn't find this in the docs. 

I'm making a discord bot to update some infos in a sheet. I want it to check if my service account has access to view or edit the sheet before it does anything. Right now if it doesnt have access it just stops my app, on both reading and writing.

im doing the authentication using a service account.

thanks.

**Comment by theoephraim** [comment]
To check it directly, I think you'd have to call the Drive API (rather than the sheets API) since that API is what handles permissions and sharing. It's on the to-do list to get some basic functionality working since it's often needed when dealing with sheets, but for the moment it is not supported.

I think if you just call `doc.useServiceAccountAuth` and wrap it in a try catch, you should be able to detect the permissions error if there is one. If that doesn't work, you should be able to just do a test reading some data. If you need to check for write access, you could do something like add and remove a sheet or a row, or add a note to a cell or something like that.

I assume things may be getting stuck because you're just not handling the errors.

**Comment by konkersgg** [comment]
After your answer I went looking for error handling.

I found this:

```
process.on('uncaughtException, err => {
    message.reply(`${err}`);
})
```

As I'm using your wrapper in a discord.js bot, I added that line inside the messageCreate event and it worked!

Sorry! I'm learning on my own. Still very new to everything. =)

Thanks <3
