### ISSUE TITLE
OH MY GOD YOU PEOPLE ARE CRAZY GAVE ME A HEADACHE

### ISSUE THREAD

**Issue by mungruez** [theoephraim/node-google-spreadsheet#538]
JUST TO READ A FEW CELLS FROM MY OWN GOOGLE SHEET WITH THE API IS TOO HARD OF A PROBLEM FOR THE ENTIRE GITHUB COMMUNITY TO SOLVE !!

YOU ARE ALL CRAZY FOOLS MAKING MORE PROBLEMS WORSE FOR ME !!!

THE GITHIB COMMUNITY IS THE PROBLEM 

NOTHING HERE WORKS BECAUSE OF YPU PEOPLE

**Comment by nparsons08** [comment]
[<img width="560" alt="Screen Shot 2022-02-05 at 12 25 03 PM" src="https://user-images.githubusercontent.com/1328388/152655981-9df72f14-a0ec-4bcd-b539-fbbc63daeaca.png">](https://g.co/kgs/NTxiR4)

**Comment by Nash0x7E2** [comment]
Instead of going on a meaningless rant, how about providing some actual information to debug the issue.

**Comment by mungruez** [comment]
Yeah , I had to let that out after being mislead about the google sheets TypeError.  This thread claims the TypeError is an error with the data type used by google sheets. This is not true the error is caused because the spreed sheet object is undefined and the values.get method is being called from a null instance. I do not like being mislead because every project I work on I can never get any help even with simple components, and this community yaps on and on about how awesome open source is and I have never used code from the open source community                                                                                                                               ----> " for decades my open source has been VS Code's boiler plate !" <-----                                                                                   The GitHub community won't even help you with simple templates far less for components .  No wonder there is a movement within the developer community that refuses to use third party software (i.e GitHub software).  Simple pieces of code snippets developers need and use all the time cannot be found on Github! Be careful not everything you read on Github is true.

**Comment by theoephraim** [comment]
There's not some vast conspiracy out there... Sometimes errors that node/js throw can be misleading or confusing. Take things one step at a time and confirm your assumptions about what is going on. If people gave you bad answers, it's probably because they just didn't understand your problem, not because they are trying to mislead you. Learning how to ask questions clearly and debug things with a community of strangers is a skill that takes many years of practice. Everyone is out here just trying to help each other with the little free time they have...

Anyway, I hope you keep learning and trying to grow as a devleoper, but if you continue to have this attitude towards the others that build the software you use (whether you realize it or not) you won't get very far.

I don't see any other issues opened by you stating your problem, but I'm sure if you open one with some info, myself or some others will be happy to try to help.

**Comment by mungruez** [comment]
You are the first person on GitHub that has ever offer me help and so really am unsure that  will help ! I have opened a discussion on the community page under software development. I am building an app for my country that lists all shops and list all products from each shop in my country. In my app I had to do everything from scratch for myself I could not get help with even a button from the GitHub community.  I don't use open source you people make me hate open source I make my own source and I hope that Microsoft is going to buy all open source one day like they did with mySQL !  If you are not a liar help me find a simple footer, contact page component for my react front end please all I can find on GitHub are components that are not reusable unless you install styled components or the react-footer repo which is a load of GitHub crap . I just want a simple jsx footer or contact page and I cannot believe how useless GitHub and the open source community is with this !  ONE THING I WAS DEFINITELY MISLEAD ABOUT IS HOW USELESS THE OPEN SOURCE COMMUNITY IS AT HELPING ME WITH SIMPLE CODE !!!!

**Comment by jasperverbeet** [comment]
Lol, I stumbled on this issue randomly. Really funny to read. Anyway, props for being so patient @theoephraim, and thanks for the hard work you put into this repo. 🥇

**Comment by mungruez** [comment]
BUNCH OF FEMBOYS
