### ISSUE TITLE
worksheets class not working with express [Reopened Bug]

### ISSUE THREAD

**Issue by F35H** [theoephraim/node-google-spreadsheet#560]
can you provide a code sample or some more info?
It definitely works for lots of people and in the tests, so it must be something specific to your usage or your document.

_Originally posted by @theoephraim in https://github.com/theoephraim/node-google-spreadsheet/issues/509#issuecomment-962388120_

const { GoogleSpreadsheet }= require("google-spreadsheet");
const express = require("express");

const app = express();
app.set("view engine", "ejs");
app.use(express.urlencoded({ extended: true }));
app.use(express.static("public"));

const creds = require("./public/credentials.json");
const doc = new GoogleSpreadsheet(
  "spreadsheetID");
let sheet = (async function () {  
  await doc.useServiceAccountAuth(creds); 
  await doc.loadInfo();  
  return doc.sheetsByIndex[0]; }() );
  
(async function () { await sheet.loadCells(); }() );

I have stumbled upon this bug. It was closed previously for a lack of info, and I believe it's the same or a similar issue.   sheet.loadCells as well as sheet.getCells appear to not exist entirely. The actual values for the sheet, however, appear to be working fine. I attempted the code workaround in the closed bug repo, and it doesn't seem to fix the issue. I have also reinstalled all the node packages. I'm running Express, Nodemon, Ejs, and google-spreadsheets.

Edit: further testing revealed it seems to have something to do with express. I removed the express code in this snippet, and it works fine. If this doesn't count as an issue due to this, closing the issue is fair. I may just move to an alternative.

**Comment by theoephraim** [comment]
From looking at the short snippet above, it appears the issue has to do with how you are using async await.

if you call two async methods in a row like this:
```
const thing1 = (async function () { ... })();
const thing2 = (async function () { ... })();
```
you're not actually waiting for that first statement to finish before continuing to the next.

versus
```
(async function () { 
  const thing1 = await ...
  const thing2 = await ... // this is actually waiting for thing1 await to finish
})();
```


normally if you're running a web server (like express), then it may be safe to initialize the sheet / auth right away with something like `const sheet = (async function () { ... })();` and then use the sheet within an async route handler. This is because you can (sort of) safely assume that by the time the web server is listening and a web request comes in, initializing the sheet will be complete.

Sometimes in a similar situation, it can be handy to use a deferred promise pattern, where you initialize a deferred promise that you can return/export right away, and then actually run your initialization how you like. Then when you go to use the thing you can first await the promise of the initialization being finished. In most cases it will already be completed, but if it isnt' it will wait correctly.

defer-promise.js
```
// useful when you need to export a promise before ready to start whatever will initialize it
// should be used sparingly
export default function defer() {
  const deferred = {
    promise: null,
    resolve: null,
    reject: null,
  };

  deferred.promise = new Promise((resolve, reject) => {
    deferred.resolve = resolve;
    deferred.reject = reject;
  });

  return deferred;
}
```

my-doc.js
```
const { GoogleSpreadsheet } = require('google-spreadsheet');
const defer = require('./defer-promise');
const creds = require('./creds');

export const myDoc = new GoogleSpreadsheet('YOUR-DOC-ID');
const docIsReadyDeferred = defer();
export const docIsReady = docIsReadyDeferred.promise;

// do your initialization... Could be invoked immediately, or wrapped in a function like `initGoogleSheet` which gets called as part of your setup code.
// The benefit here is that youre not necessarily waiting for this to be complete while other stuff is going on
(async function() {
  try {
    await doc.useServiceAccountAuth(creds);
    docIsReadyDeferred.resolve(); // manually resolving the promise after the doc is ready to be used
  } catch (err) {
    docIsReadyDeferred.reject(err);
})();
```

some-other-script.js
```
const { docIsReady, myDoc } = require('./my-doc');

// for example in an express route handler
app.get('/some-route', async (req, res, next) => {
  await docIsReady; // usually already done
  // ...
});
```

Hope that is helpful!

**Comment by F35H** [comment]
Thank you. I must have been tired that night as this explanation makes perfect sense. Granted, that doesn't really explain why it doesn't load the function until loadCells is run.

Javascript is not my main language as you can probably tell.
