### ISSUE TITLE
OAuth 2.0 part with a command not documented/described

### ISSUE THREAD

**Issue by Productivix** [theoephraim/node-google-spreadsheet#564]
Hi Theo, 
I studdied your page https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication?id=oauth
and I did not understand where in §4 was documented / described the command "fetchUserGoogleCredsFromDatabase" ?
thanks

**Comment by theoephraim** [comment]
That's just a placeholder/example...

In the OAuth use case (rather than using a service account) it is likely you are connecting on behalf of multiple specific users, and so you'd most likely be saving those credentials in a database. This method is just a placeholder for "fetch the oauth creds/tokens from wherever you saved them".
