### ISSUE TITLE
Exclude some fields in getRows

### ISSUE THREAD

**Issue by mrgoos** [theoephraim/node-google-spreadsheet#67]
Hi,
When executing getRows I see those properties in the object response:
_xml, id, _links, save, del
Is there a way to call getRows and get only the rows under columns?

Thanks.

**Comment by theoephraim** [comment]
This would probably require a bit of refactoring in how the data is stored.
You could filter out properties that start with "_" and also filter out properties that have a type of function?

**Comment by piranna** [comment]
Maybe they could be set as not enumerable properties?

**Comment by piranna** [comment]
I've fixed this on #73 because I've got the same problem.

**Comment by mrgoos** [comment]
Cool!

**Comment by theoephraim** [comment]
Should be easy to make a new PR now to fix this, and the tests should catch any problems!

**Comment by yipcma** [comment]
I'm curious whether this is implemented.

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
