### ISSUE TITLE
support duplicate headers

### ISSUE THREAD

**Issue by MathRobin** [theoephraim/node-google-spreadsheet#673]
In this library code, you provid mechanism to forbid duplicate headers for non-empty strings. But this is too coercitive. A google spreadsheet can have duplicate header values
![Capture d’écran du 2024-01-02 16-32-00](https://github.com/theoephraim/node-google-spreadsheet/assets/1046585/1854598f-4e5d-4905-b300-36486d48a0dd)
I put as attachment a screenshot which shows that it's possible without any problem.

Maybe you have a business case that need headers to be unique, but it's opinionated.

I tried to only setup data rows without setting header row, but your library doesn't allow it. Anyway to trick this ? Anyway to disable duplicate header control ?

**Comment by MathRobin** [comment]
Have found a workaround:
```javascript
worksheet._headerValues = [];
await worksheet.addRows(rows);
```
quick&dirty but working

**Comment by vlucas** [comment]
I have this same issue. I find the duplicate header error to be too restrictive, and causes issues with many users in real-world scenarios. Speadsheets from average users are messy, and the code in this library should account for that.

Instead of throwing an error when duplicate headers are found, just pick the first one and use that. So if there are two headers named "Date" or whatever, just use the first one you find and ignore the other. This will ensure that data always gets inserted, even if the actual spreadsheet is a bit messy.

**Comment by MathRobin** [comment]
Agree and disagree.
Ok that spreadsheet of average users are messy but it could be a use-case too, to have duplicate headers (aka "first row") when it's only for calc or storage (for a formula in another sheet).

So I think the best solution is to provide setHeaders method without control of duplicate, or with optional control. We shouldn't use the solution : "take care of first occurence, forget the others", which is opinionated too.

**Comment by MathRobin** [comment]
I tried to build a PR but wasn't able to build project locally just after clone. Any help @theoephraim ?

**Comment by theoephraim** [comment]
Of course you can have whatever data in whatever cells you want as it is just a spreadsheet. However the row-based API provided by this module is making an explicit trade-off of simplicity in exchange for some limitations and is designed for the use case of when you want to use your spreadsheet _like a database_. In a database you cannot have duplicate columns. This api also lets us convert rows into objects - using columns as keys - where you cannot have duplicate keys.

In my opinion, in the case of duplicate headers the most reasonable/intuitive thing to do is explode if we detect dupes... Taking the first one would also certainly work, but I think it would cause more confusion than the convenience is worth.

Any other solution would mean adding complexity to how you interact with rows and is in my opinion probably not worth it. 
Especially since 99% of the time if you are using this module you will also have control over the spreadsheet, it seems fairly reasonable to me to just say - dont use duplicate headers. You can easily adjust one to make it more explicit or even just add a number to avoid the duplicate value.

You can always fall back to the cell-based methods if you want to write any data into any cells and are not using your sheet like a database.

That all said, if you want to propose some way to support duplicate headers that keeps things simple and won't lead to unexpected confusion, I'll certainly consider it... but I can't think of any easy way to do that.

@MathRobin - I'll need more details about the errors you are getting when trying to run/build the project locally... Feel free to open a new issue with that info.

**Comment by MathRobin** [comment]
@theoephraim i was trying to build with yarn and just realized that you used pnpm on this project. When trying with pnpm, everything is building. So it's ok now to suggest some changes :smile_cat:

**Comment by abhishekpathak-bitkraft** [comment]
Is the issue fixed? (for confirmation)
I am still getting 
`error while createHeader:  Error: Duplicate header detected: "apple". Please make sure all non-empty headers are unique`

**Comment by ilnuribat** [comment]
I had issue when `getRows()` doesn't return columns data if header of these columns are empty
I want to get all data from sheet

**Comment by theoephraim** [comment]
That’s just how the row-based methods work. Use the cell based methods if you want to get everything.

**Comment by MathRobin** [comment]
not linked to my original question. I've suggested a workaround for my problem. No this is closed.
And we don't use anymore this repo.

Bye
