### ISSUE TITLE
triggerUncaughtException error occurred

### ISSUE THREAD

**Issue by G-hoon** [theoephraim/node-google-spreadsheet#708]
![image](https://github.com/user-attachments/assets/f664aabb-a9f0-498b-9fbd-e03988333bfd)

I'm trying to get data from google spread sheet.
but below error occurred.

![image](https://github.com/user-attachments/assets/d44c0899-ce02-422d-86be-64228022bd51)

and my package.json is like that.

![image](https://github.com/user-attachments/assets/f18b2df4-5188-412c-82e8-02eb1f4eba40)

**Comment by theoephraim** [comment]
it looks like you're expecting the creds to be loaded into `process.env`, I assume because you added the `dotenv` they are in a `.env` file? You'll need to make suer you actually load the .env file, it doesn't just happen on its own. Although nodejs does have some very basic support for this...

For a much more full-featured solution, I suggest you try out http://dmno.dev
