### ISSUE TITLE
Error: HTTP error 412: Precondition Failed "Mismatch: etags

### ISSUE THREAD

**Issue by lprhodes** [theoephraim/node-google-spreadsheet#71]
Hey,

Using 1.1.3 I'm getting the following error when saving a row for the second time (having waited for the first save to call its callback).

Error: HTTP error 412: Precondition Failed "Mismatch: etags = [&quot;AxNaRiw9OCG7ImA9DEgAGBQ.&quot;], version = [1gn9l5sgj227p]"

(I've changed some of the characters above in case any of them were tokens.)

I'm using it to change the text in a cell to "Sending" and then once I've performed the necessary actions I update it to "Sent".

Any ideas?

Thanks!

Luke

**Comment by theoephraim** [comment]
Sounds like the etags in the XML that gets sent needs to be updated after the first save.
Shouldn't be too difficult to get working!

I'll try to get to it soon! Pull requests also welcome!

Keep in mind, this all works in kind of a nasty way, just naively saving the original XML and doing find/replaces on it. This is because when I originally wrote the library, doing any kind of conversion from a parsed structure back to XML wasn't working. It seems google's formatting is (or was?) very strict.

**Comment by theoephraim** [comment]
Just released a big update and I think this issue is all fixed.
I'm not dealing with the individual etag values, but just sending the right if-match headers all the time.
Please upgrade to the latest version and let me know if you are still having problems. Thanks :)

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Thanks! 😄
