### ISSUE TITLE
Use this in front end

### ISSUE THREAD

**Issue by kevin1193** [theoephraim/node-google-spreadsheet#81]
When I used browserify to used this module in front end I encountered this issue.

Uncaught TypeError: fs.readFileSync is not a function. Kindly please show how could I used this in front end.

Best Regards,
Kevin Abestilla

**Comment by theoephraim** [comment]
I dont see any reason why it couldn't work, except you would have to pass in the credentials as an object instead of loading the service account file. Try it out and let me know if it works!

**Comment by saadq** [comment]
I think this is the same issue from [32](https://github.com/theoephraim/node-google-spreadsheet/issues/32). I am also getting this issue – it seems when you try to load this module using `require("google-spreadsheet")` in the client with Browserify it throws that error before even using it :/

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
